### ISSUE TITLE
Cannot sign in to any server

### ISSUE THREAD

**Issue by pro-sumer** [elk-zone/elk-native#9] opened 2023-01-09 15:31 UTC
Whatever server I try, I cannot sign in using the Native Elk App (I have been able to sign in using the web version of Elk on the same servers some time ago).

<img width="912" alt="Sign in dialog with error message 'Cannot connect to the server'" src="https://user-images.githubusercontent.com/44335102/211333243-3a0e9cc2-a8ed-48d6-8dd2-9489236cc4ce.png">

**Comment by sxzz** [comment] 2023-01-09 15:41
Duplicate of #2

**Closed** 2023-01-13 08:23 UTC
